server:
  port: 8088
  
spring:
   application:
      name: integra-config-server
   cloud:
       config:
           server:
              git:
                uri: file://C:/dev/integra-microservices-config
                #uri: file://opt/apps/integra-microservices-config
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false    
