server:
  port: 8088
  
spring:
   application:
      name: integra-config-server
   cloud:
       config:
           server:
              git:
                #uri: file://C:/dev/integra-microservices-config
                uri: file://home/jsoares/integra-config-server-arquivos
           
eureka:
  client:
     serviceUrl:
        defaultZone: http://integra-eureka:8761/eureka
#    fetch-registry: false
#    register-with-eureka: false    
